project_id = "nxlncqmwpjiufsnwkfnd"

[functions.coingecko-proxy]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.paddle-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.paddle-portal]
verify_jwt = false
