project_id = "nxlncqmwpjiufsnwkfnd"

[functions.coingecko-proxy]
verify_jwt = false

[functions.stablecoins-proxy]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.yoco-checkout]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false
